def getProducts():
    products = []
    products.append(('Mobiles & Accessories',['Mobiles','Power Bank Pouches','Tablets','Mobile Accessories','Tablet Accessories','Landline Phones']))   
    products.append(('Mobiles',))
    products.append(('Tablets',))
    products.append(('Power Bank Pouches',))
    products.append(('Mobile Accessories',['Cases & Covers','Mobile Enhancements','Screen Protectors','Chargers','Cables','Styling & Maintenance','Power Banks','Car Accessories','Headsets (Mic)','Headphones','Stylus Pens','Batteries','Speakers','Memory Cards & Readers','Bluetooth Headsets (Mic)','Headphone Splitters','Smart Watches','Headphone Amplifiers','SIM Adapters','Sim Cutters','Charging Pads']))
    products.append(('Cases & Covers',))
    products.append(('Mobile Enhancements',['Mobiles Accessories Combos','Docking Stations']))
    products.append(('Mobile Accessories Combos',))
    products.append(('Docking Stations',))
    products.append(('Screen Protectors',))
    products.append(('Chargers',['Wall Chargers','Portable Chargers','Car Chargers','Travel Adapters','Wireless Chargers']))
    products.append(('Wall Chargers',))
    products.append(('Portable Chargers',))
    products.append(('Car Chargers',))
    products.append(('Travel Adapters',))
    products.append(('Wireless Chargers',))
    products.append(('Cables',))
    products.append(('Styling & Maintenance',['Skins','Cleaning Kits','Phone Charms','Replacement Screens']))
    products.append(('Skins',))
    products.append(('Cleaning Kits',))
    products.append(('Phone Charms',))
    products.append(('Replacement Screens',))
    products.append(('Power Banks',))
    products.append(('Car Accessories',['Car Chargers','Mobile Holders','Car Kits','GPS Navigation Devices']))
    products.append(('Car Chargers',))
    products.append(('Mobile Holders',))
    products.append(('Car Kits',))
    products.append(('GPS Navigation Devices',))
    products.append(('Headsets (Mic)',))
    products.append(('Headphones',))
    products.append(('Stylus Pens',))
    products.append(('Batteries',))
    products.append(('Speakers',))
    products.append(('Memory Cards & Readers',['Mobile Memory Cards','Card Readers']))
    products.append(('Mobile Memory Cards',))
    products.append(('Card Readers',))
    products.append(('Bluetooth Headsets (Mic)',))
    products.append(('Headphones Splitters',))
    products.append(('Smart Watches',))
    products.append(('Headphone Amplifiers',))
    products.append(('Sim Adapters',))
    products.append(('Sim Cutters',))
    products.append(('Charging Pads',))
    products.append(('Tablet Accessories',['Tablet Cases & Covers','Tablet Screen Protectors','Tablet Chargers','Tablet Speakers','Tablet Cables','Tablet Memory Cards & Readers','Tablet Keyboards','Tablet Stylus Pens','Tablet Headphones','Tablet Bluetooth Devices (Mic)']))
    products.append(('Tablet Cases & Covers',))
    products.append(('Tablet Screen Protectors',))
    products.append(('Tablet Chargers',['Tablet Portable Chargers']))
    products.append(('Tablet Portable Chargers',))
    products.append(('Tablet Memory Cards & Readers',['Tablet Memory Cards']))
    products.append(('Tablet Memory Cards',))
    products.append(('Tablet Speakers',))
    products.append(('Tablet Cables',))
    products.append(('Tablet Keyboards',))
    products.append(('Tablet Stylus Pens',))
    products.append(('Tablet Headphones',))
    products.append(('Tablet Bluetooth Headsets (Mic)',))
    products.append(('Landline Phones',))
    products.append(('Footwear',['Men\'s Footwear','Women\'s Footwear','Kid\'s Footwear']))
    products.append(('Men\'s Footwear',['Men Shoes','Men Sandals & Floaters','Men Slippers & Flip Flop']))
    products.append(('Men Shoes',['Men Casual Shoes','Men Sports Shoes','Men Formal Shoes','Men Ethnic Shoes']))
    products.append(('Men Casual Shoes',))
    products.append(('Men Sports Shoes',))
    products.append(('Men Formal Shoes',))
    products.append(('Men Ethnic Shoes',))
    products.append(('Men Sandals & Floaters',))
    products.append(('Men Slippers & Flip Flop',))
    products.append(('Women\'s Footwear',['Women Flats','Women Bellies','Women Heels','Women Wedges','Women Formal','Women Casual Shoes','Women Sports Shoes','Women Sports Sandals','Women Slippers & Flip Flop','Women Sandals']))
    products.append(('Women Flats',))
    products.append(('Women Bellies',))
    products.append(('Women Heels',))
    products.append(('Women Wedges',))
    products.append(('Women Formal',))
    products.append(('Women Casual Shoes',['Women Lifestyle','Women Loafers','Women Mocassins','Women Sneakers','Women Canvas','Women Boots']))
    products.append(('Women Lifestyle',))
    products.append(('Women Loafers',))
    products.append(('Women Mocassins',))
    products.append(('Women Sneakers',))
    products.append(('Women Canvas',))
    products.append(('Women Boots',))
    products.append(('Women Sports Shoes',['Women Trekking & Outdoors','Women Gym & Fitness','Women Running','Women Tennis','Women Walking']))
    products.append(('Women Trekking & Outdoors',))
    products.append(('Women Gym & Fitness',))
    products.append(('Women Running',))
    products.append(('Women Tennis',))
    products.append(('Women Walking',))
    products.append(('Women Sports Sandals',))
    products.append(('Women Slippers & Flip Flop',))
    products.append(('Women Sandals',['Women Formal Sandals']))
    products.append(('Women Formal Sandals',))
    products.append(('Kid\'s Footwear',['Girls','Boys']))
    products.append(('Girls',['Girls Sandals','Girls Clogs','Girls Flats & Bellies','Girls Casual Shoes','Girls Sports Shoes','Girls School Shoes','Girls Slippers & Flip Flop','Girls Booties']))
    products.append(('Girls Sandals',['Girls Sports Sandal','Girls Casual Sandals']))
    products.append(('Girls Sports Sandals',))
    products.append(('Girls Casual Sandals',))
    products.append(('Girls Clogs',))
    products.append(('Girls Flats & Bellies',['Girls Flats','Girls Bellies']))
    products.append(('Girls Flats',))
    products.append(('Girls Bellies',))
    products.append(('Girls Casual Shoes',))
    products.append(('Girls Sports Shoes',))
    products.append(('Girls School Shoes',))
    products.append(('Girls Slippers & Flip Flop',))
    products.append(('Girls Booties',))
    products.append(('Boys',['Boys Sandals','Boys Clogs','Boys Casual Shoes','Boys Sports Shoes','Boys School Shoes','Boys Slippers & Flip Flop']))
    products.append(('Boys Sandals',['Boys Casual Sandals','Boys Sports Sandals']))
    products.append(('Boys Casual Sandals',))
    products.append(('Boys Sports Sandals',))
    products.append(('Boys Clogs',))
    products.append(('Boys Casual Shoes',))
    products.append(('Boys Sports Shoes',))
    products.append(('Boys School Shoes',))
    products.append(('Boys Slippers & Flip Flop',))

    return products